### ISSUE TITLE
Doesn't work /snyk page [🐛]

### ISSUE THREAD

**Issue by freeart** [snyk-tech-services/backstage-plugin-snyk#123]
- `node -v`: v16.16.0
- `npm -v`: 8.11.0
- OS: OSX

### Expected behaviour
/snyk page should be shown

### Actual behaviour
URL changes to https://xxx/snyk
no changes on the screen, no errors in the console

### Steps to reproduce
Install the plugin as described
Click on "Across xx projects ->" link

**Comment by aarlaud** [comment]
Hi there, I'm not able to reproduce the problem. I register a component and clicking on that link sends me to the security tab as expected. Can you share more details on what you are experiencing?
thanks!
