### ISSUE TITLE
[🐛] LinkInfo from Table in EntityPage it's hardcoded

### ISSUE THREAD

**Issue by antoniobergas** [snyk-tech-services/backstage-plugin-snyk#136]
Hi! 

We are adopting snyk with a self-hosted instance (also using broker with azure devops self-hosted)

The plugin works perfectly but in the Entity Component Page (Sorry if its wrong)
the linkInfo that redirects you to the selected project in the snyk UI its hardcoded with the cloud hosted version (https://app.snyk.io/)

Will be great to have the host comming from the app-config.yml as we already have it pointing to the self-hosted instance, maybe using the configApi (or discoveryApi.getBaseUrl() in case you have backend plugin)

Thanks a lot for the good work 😊

![image](https://user-images.githubusercontent.com/26031467/228253209-626b6bd2-32ab-4290-ad33-11a7fb553ce8.png)

https://github.com/snyk-tech-services/backstage-plugin-snyk/blame/81422bc4890e6fc9ea6fffb7302f6f7010d786de/src/components/SnykEntityComponent/snykTab.tsx#L83

**Comment by aarlaud** [comment]
Hi there, thanks for the kind words ☺️
I'm not sure what you mean by self hosted precisely but i suppose you're referring to a different region or at least snyk hostname? 
I'll take a look shortly

**Comment by antoniobergas** [comment]
With self-hosted I mean that we run the broker for Azure DevOps Server (I think we use a docker image provided by Snyk) So our host its https://app.eu.snyk.io

**Comment by aarlaud** [comment]
hey, can you give 1.2.9 a shot? please let me know how it goes.

**Comment by antoniobergas** [comment]
Works great!! Thanks a lot for the help and the fast reply 😊
