### ISSUE TITLE
[🙏] need feature to filter with project id as optional instead of pulling all projects in target

### ISSUE THREAD

**Issue by naresh1919** [snyk-tech-services/backstage-plugin-snyk#147]
**Describe the user need**

i need a feature of project-id as optional annotation, If we provide it it has to pull these projects only instead of pulling all projects pulling from target
in some of my bitbucket repos using as shared repos, There is multiple pom files are present in single repo and each application owner may changes, so we can't provide the all project snyk reports to each developer which they won't own
i am requesting to add this feature to avoid un necessary confusion to developers

**Describe expected behaviour**

i need a optional project ids filter to pull those projects only from the target instead of pulling all projects

**Comment by aarlaud** [comment]
#157 will bring you lots more options to specify target(s), project IDs, targets with some project IDs to exclude, so hopefully you'll be able to find the right combination of settings that suit your needs.

I'm closing this out but once this version is in, please open a new issue if anything still after the new version brought by #157 is in.
