### ISSUE TITLE
[🐛]clicking on any redirecting url to snyk is getting wrong snyk url

### ISSUE THREAD

**Issue by naresh1919** [snyk-tech-services/backstage-plugin-snyk#148]
- `node -v`: 18
- `npm -v`: 9.5.1
- OS: MACOS
- Command run: (e.g. `snyk-api-import ...`, ...)

### Expected behaviour
when we click on more data button at below of snyk reports, It has to redirect snyk ui regarding project location 

### Actual behaviour
its getting error like 
"Unable to display this organization
The organization does not exist, or you do not have permission to access it.

If the problem persists, please [contact support](mailto:support@snyk.io) with reference ID "

not only more data button all redirection urls to snyk are getting same issue, they are getting with org id in redirection url instead of org name, that getting issue wrong org in snyk ui, it should get org name instead org id in redirection url

### Steps to reproduce
1.select "your Component" in backstage
2. goto "Security"
3. select "any of your snyk project"
4. come down of the page
5. click on "more data"

### Screenshots

<img width="1347" alt="Screenshot 2023-07-13 at 1 06 36 PM" src="https://github.com/snyk-tech-services/backstage-plugin-snyk/assets/49805554/1d2cd774-4b87-4524-ab41-ae5f5b6d81bc">

**Comment by aarlaud** [comment]
ACK. will look to fix that shortly. leftovers from the previous version...

**Comment by aarlaud** [comment]
2.0.1 should fix that. thanks !
