### ISSUE TITLE
[🐛] Discovering projects from `github.com/project-slug` limits results to only 10 projects

### ISSUE THREAD

**Issue by alecjacobs5401** [snyk-tech-services/backstage-plugin-snyk#150]
- `node -v`: `v16.14.0`
- `npm -v`: `8.3.1`
- OS: OSX
- Command run: Backstage Plugin

### Expected behaviour
GitHub Repos with >10 Projects should display all Projects when discovering by `github.com/project-slug` annotation

### Actual behaviour
Default page limit of 10 is only being returned, so not all projects are shown. Additionally, all tabs show the source of the project (e.g. `yarn`) instead of the project name, so the tabbed view is really hard to use.

![image](https://github.com/snyk-tech-services/backstage-plugin-snyk/assets/12898497/18b796ce-563f-4ea1-a534-fc0231e6d703)

### Steps to reproduce
1. Have a GitHub repo with >10 combined Dockerfiles, package.json, etc. (e.g, a Backstage repo with internal plugins)
2. Configure `backstage-plugin-snyk` and configure an Entity as defined in docs

### Debug log
N/A

### Screenshots
N/A

**Comment by alecjacobs5401** [comment]
Ideally, the name of the target/project would be nice, but I understand that there is definitely limited real estate. Maybe truncated text in the tab (with a tooltip that has the full title)?

Thanks for the fast follow up!

**Comment by aarlaud** [comment]
2.0.1 should pull up to 100 projects now. Tried the best I could UI wise, but 1) I'm not the best UI designer :smile: and 2) customizing the Backstage core components is not something I've understood yet, so adding a tooltip on the tab title is not something I know how to do at this stage.
Hoping it'll work out however. might need a few more UI tweaks possibly, we'll see.

**Comment by alecjacobs5401** [comment]
@aarlaud Thanks! Looks great - much appreciate the quick turnaround time!

**Comment by aarlaud** [comment]
closing this out.
