### ISSUE TITLE
[🐛]

### ISSUE THREAD

**Issue by TheDaemonBarber** [snyk-tech-services/backstage-plugin-snyk#152]
### Expected behaviour
the annotation snyk.io/target-id implies that you need the GUID style target id, but it is actually the target name

### Actual behaviour
either the annotation needs to be renamed to target-name or it should accept the target id

**Comment by aarlaud** [comment]
Hi,

the target ID annotation expects the target ID. The target name is something that is expected currently via github.com/project-slug and soon will be instead source-location.
What's the issue you're facing exactly?

**Comment by TheDaemonBarber** [comment]
Hi sorry for the late response.

I can use the Target name for the value - this works too, not just the target-id
 However now that I can use the target-id annotation, the links to individual issues from the plugin no longer works, the links are malformed.

**Comment by aarlaud** [comment]
Can you share a bit more details about the malformed links? Screenshot and/or example of malformed link?
I'm not seeing issues in my sampling tests

**Comment by aarlaud** [comment]
Closing this. I believe it was fixed, but please re open something if necessary. thanks
