### ISSUE TITLE
[🐛] snyk.io/target-id should take precedence over github.com/project-slug to list projects

### ISSUE THREAD

**Issue by Vity01** [snyk-tech-services/backstage-plugin-snyk#155]
`snyk.io/target-id` is more specific than `github.com/project-slug` (you can define multiple targets, not just 1 repo), but the used project list is loaded by shared `github.com/project-slug` . 
It should apply for all components (Overview, SnykEntityComponent).

By default, Snyk CLI generates project names with "org/reponame.git" (with .git extension) which clashes with `github.com/project-slug` [definition](https://backstage.io/docs/features/software-catalog/well-known-annotations/#githubcomproject-slug) and some plugins cannot use it in this format (with the .git extension). Therefore we would like to use the `snyk.io/target-id` as an alternative. 
It should be easy to fix [SnykOverviewComponent.tsx](https://github.com/snyk-tech-services/backstage-plugin-snyk/blob/0292ae8926936861acdc72345077ce2a4f90e388/src/components/SnykEntityComponent/SnykOverviewComponent.tsx#L73-L73), just to switch usage of the annotation values.
It's good idea to use `project-slug`, but IMHO the Snyk CLI should not include `.git` prefix into the name by default or the search by name should support it (same as Github, it takes both variants in URL).

**Comment by aarlaud** [comment]
I'm about to push out a version (#157) where everything is additive and specifically list out the projects you want to exclude if any. would that address your need?

**Comment by Vity01** [comment]
I am not sure. Will the `target-id` take precedence before `project-slug` ?

**Comment by aarlaud** [comment]
> I am not sure. Will the `target-id` take precedence before `project-slug` ?

Sorry for the delay in response, it's actually project-slug (SNYK_ANNOTATION_TARGETNAME) OR target-id (SNYK_ANNOTATION_TARGETID) in this case.
```
if (annotations?.[SNYK_ANNOTATION_TARGETNAME]) {
      targetsArray.push(annotations?.[SNYK_ANNOTATION_TARGETNAME]);
    } else if (annotations?.[SNYK_ANNOTATION_TARGETID]) {
      targetsArray.push(annotations?.[SNYK_ANNOTATION_TARGETID]);
    }
```

With that said, you have the ability to pass multiple targets if need be, in addition to the project-slug possibly, so you can add them in an array for the annotation "snyk.io/targets". Logic is [there](https://github.com/snyk-tech-services/backstage-plugin-snyk/blob/e11d94c74b45937a800c1a3eebbb3fdbe2bd7edf/src/api/index.ts#L139)

**Comment by aarlaud** [comment]
Closing this. Let me know if the current configuration knobs present issues.
