### ISSUE TITLE
[🐛] Snyk count does not match the one from Snyk app.snyk.io (official website)

### ISSUE THREAD

**Issue by nnillni** [snyk-tech-services/backstage-plugin-snyk#161]
- `node -v`:
- `npm -v`:
- OS: (e.g. OSX, Linux, Windows, ...)
- Command run: (e.g. `snyk-api-import ...`, ...)

https://github.com/snyk-tech-services/backstage-plugin-snyk/pull/163

### Expected behaviour
The count of vulnerabilities of critical/high/medium/low from the Backstage Plugin and the ones from the app.snyk.io (official website) must match.

### Actual behaviour
They do not match, I get 7 critical vulnerabilities for backstage itself for `packages/backend/package.json` with the plugin (more) than in the website where there are 0 critical vulnerabilities reported. Same happens with other `project-ids` where the plugin shows more than the official website.

I have noticed the plugin code does not check for the `status` = `resolved` in the `issue` data returned by the API, which seems to be what makes the difference (?). I am not sure if this `status` field refers to the CVE vulnerability being resolved or **your actual issue** being resolved, but to me it seems to be the **later**, so the counts would match like in the official website.

I might be wrong but it just seems like a bug to me, because I cannot reproduce having any vulnerability locally nor on the official website and the plugin keeps saying so

### Steps to reproduce
Just add any project-id and the count mismatches, in the screenshots section I will show the code I was referring too and the behaviour I see

### Screenshots
**Vulnerability mismatch**
<img width="277" alt="image" src="https://github.com/snyk-tech-services/backstage-plugin-snyk/assets/40041725/38e42699-cb39-42d5-aec3-2b7163468298">
<img width="360" alt="image" src="https://github.com/snyk-tech-services/backstage-plugin-snyk/assets/40041725/05588720-3c4f-4dc1-b2c4-aedd188c3ef7">

**Code not checking for the status field (resolved vs open)**
<img width="1156" alt="image" src="https://github.com/snyk-tech-services/backstage-plugin-snyk/assets/40041725/4194afd5-a0d2-4a30-a8a1-10dd089b17a3">
<img width="656" alt="image" src="https://github.com/snyk-tech-services/backstage-plugin-snyk/assets/40041725/6d474bd9-8db0-4302-a46e-fd167372adeb">
<img width="589" alt="image" src="https://github.com/snyk-tech-services/backstage-plugin-snyk/assets/40041725/cb43f36c-33b0-4c58-9123-74504670c602">

**API returning the issue status + proof that it is fixed**
* It is reporting this vulnerability from backstage < 1.15, when my app is on 1.19 (latest)
<img width="742" alt="image" src="https://github.com/snyk-tech-services/backstage-plugin-snyk/assets/40041725/99a87a0e-1a70-4da2-a396-050b8604e06a">
* API returns the issue with `resolved` status, and the official website is not showing the vulnerability but the package does
<img width="701" alt="image" src="https://github.com/snyk-tech-services/backstage-plugin-snyk/assets/40041725/02cbde11-d1d6-48d7-8297-b7013c0f1af1">
<img width="1270" alt="image" src="https://github.com/snyk-tech-services/backstage-plugin-snyk/assets/40041725/288ca179-be56-4886-b3f9-925fddd7c0b0">

---------

### **PS:**
**I just noticed that the plugin in the security tab shows which ones are open/resolved.**
**Maybe this was intended but to me it makes no sense that the overview keeps showing vulnerabilities the developers have already resolved (?).** 

**Maybe we can filter them out with an option if we don't want to make a breaking change to the current adopters (?)
Thanks**

**Comment by aarlaud** [comment]
Thanks for the feedback. I'll review this asap.

**Comment by aarlaud** [comment]
For information, this is aimed to be fixed in https://github.com/snyk-tech-services/backstage-plugin-snyk/pull/163

**Comment by aarlaud** [comment]
merged.
