### ISSUE TITLE
Error: ignored vulnerabilities are count in overview component

### ISSUE THREAD

**Issue by antoniobergas** [snyk-tech-services/backstage-plugin-snyk#176]
https://github.com/snyk-tech-services/backstage-plugin-snyk/blob/9159a8faebb56c650c1489e3d5831bd750810e5c/src/components/SnykEntityComponent/SnykOverviewComponent.tsx#L67C1-L104C51

Hello! I just updated to the latest version of the plugin and everything looks great! Thanks for the hard work.

I'm currently analazyng a little bit about what it's shown in the UI and when I have a component that have ignored vulnerabilities, the overview component count them anyways.

Is this the desired behaviour? From our side seems confusing, evendo in the security tab section everything it's green

**Comment by aarlaud** [comment]
Hum, I think this [function](https://github.com/snyk-tech-services/backstage-plugin-snyk/blob/9159a8faebb56c650c1489e3d5831bd750810e5c/src/api/index.ts#L145) doesn't exclude the ignored issue in this flow. Need to fix this indeed.

**Comment by antoniobergas** [comment]
Great! Thanks a lot! Let me know if you need a hand 😁
