### ISSUE TITLE
API version change leads to Bad Request

### ISSUE THREAD

**Issue by swnia** [snyk-tech-services/backstage-plugin-snyk#177]
With the new default version that is used, [this API call](https://github.com/snyk-tech-services/backstage-plugin-snyk/blob/9159a8faebb56c650c1489e3d5831bd750810e5c/src/api/index.ts#L342) will lead to a 400 when using project slugs as they contain slashes.

Either the documentation in the README should be updated or a default URL-encoding should be added when generating the URL.

**Comment by swnia** [comment]
The following blocks would probably fix this [here](https://github.com/snyk-tech-services/backstage-plugin-snyk/blob/9159a8faebb56c650c1489e3d5831bd750810e5c/src/api/index.ts#L304)
```typescript
for (let i = 0; i < repoName.length; i++) {
      try {
        TargetIdsArray.push(
          `target_id=${encodeURIComponent(await this.getTargetId(orgId, repoName[i]))}`
        );
      } catch (e) {
        if (!ignoreMissing) throw e
      }
    }
```
and [here](https://github.com/snyk-tech-services/backstage-plugin-snyk/blob/9159a8faebb56c650c1489e3d5831bd750810e5c/src/api/index.ts#L342)
```typescript
const projectsForTargetUrl = `${backendBaseUrl}/rest/orgs/${orgId}/projects?ids=${encodeURIComponent(projectIdsArray.join(
      "%2C"
    ))}&limit=100&version=${version}`;
```

**Comment by aarlaud** [comment]
thanks for the note. will push a fix asap

**Comment by aarlaud** [comment]
Hi there, actually I'm not sure I can reproduce the issue. Can you give me an example of the issue when you're seeing. I'll need an example annotation I think. The target I'm using has a slash in it and it's working fine.

**Comment by swnia** [comment]
So, the issue pops up for version `2023-06-19~experimental` and an ids parameter mixing a slug and ids. In my case, it's a slug first and then some ids like `/my/repo.git,7439e322-f9c1-4c42-8367-002b33b9d946,db066cb9-b373-46da-b918-b49b541e0d63,4737fc9c-3894-40ba-9dc5-aa8ae658c9f6` which returns a 400 with this payload
```javascript
{
    "jsonapi": {
        "version": "1.0"
    },
    "errors": [
        {
            "id": "[ID]",
            "links": {
                "about": "https://docs.snyk.io/more-info/error-catalog#snyk-openapi-0001"
            },
            "status": "400",
            "code": "SNYK-OPENAPI-0001",
            "title": "Bad request",
            "detail": "Parameter 'ids' must be url encoded. Its value may not contain reserved characters.",
            "meta": {
                "links": [
                    "https://docs.snyk.io/snyk-api-info/getting-started-using-snyk-rest-api "
                ]
            },
            "source": {
                "parameter": "ids"
            }
        }
    ]
}
```

**Comment by aarlaud** [comment]
hum, I don't think we're supporting mixed names and IDs today. What annotation do you put this under?

**Comment by swnia** [comment]
It's under `snyk.io/project-ids`

**Comment by swnia** [comment]
So, I misinterpreted [this line](https://github.com/snyk-tech-services/backstage-plugin-snyk/blob/cb713ae044f0d2ed50e1db2503c60261054137eb/README.md?plain=1#L136) as supporting both and being mixable.
Could we update that to make it clearer what is supposed to go where?
