### ISSUE TITLE
[🐛] Plugin suddenly only returns 404

### ISSUE THREAD

**Issue by swnia** [snyk-tech-services/backstage-plugin-snyk#185]
- `node -v`: v20.11.1
- `npm -v`: 10.2.4

### Expected behaviour
Before updating to version 2.2.2 the plugin returned a list of findings for an entity. Ideally, that would still happen

### Actual behaviour
An error is shown due to a 404 returned from the backend/API.

### Screenshots
<img width="343" src="https://github.com/snyk-tech-services/backstage-plugin-snyk/assets/119884634/0e2c3744-466d-499b-ac1f-7a82daaaae25">
<img width="948" src="https://github.com/snyk-tech-services/backstage-plugin-snyk/assets/119884634/98fdca53-16d9-41e9-acae-bd608cbd6f5d">

**Comment by aarlaud** [comment]
Can you create a support ticket so we can investigate a bit? I'll need to check the parts you redacted
