### ISSUE TITLE
[🙏] `isSnykAvailable` function, and display information on how to configure instead of that gif

### ISSUE THREAD

**Issue by ghost** [snyk-tech-services/backstage-plugin-snyk#60]
**Describe the user need**
I would like a `isSnykAvailable` so i can do:
```
    <EntitySwitch>
      <EntitySwitch.Case if={isSnykAvailable}>
        <Grid item md={6} xs={12}>
          <SnykOverview />
        </Grid>
      </EntitySwitch.Case>
    </EntitySwitch>
```

**Describe expected behaviour**

When Snyk is not available, the big gif of John Travolta is showing. This is not a very good user experience.

**Additional context**

When Snyk is not available, it would also be nicer to show how to configure it, instead of that horrible gif.

**Comment by aarlaud** [comment]
ACK.

**Comment by KimboTodd** [comment]
Hello, that gif is wonderful. It genuinely brought a smile to my face in while debugging and I appreciate something to lighten the mood while running into errors. The error message did point me to check and see if my annotations were wrong 

> Seems we are missing some references, check out the annotations in [java-goof-component.yaml](https://github.com/snyk-tech-services/backstage-test/blob/master/java-goof-component.yaml).

Unfortunately it looks like java-goof-component.yaml no longer exists.
