### ISSUE TITLE
[🙏] use the `MissingAnnotationEmptyState` instead of the meme gif

### ISSUE THREAD

**Issue by ghost** [snyk-tech-services/backstage-plugin-snyk#63]
**Describe the user need**

I would like the Snyk plugin to produce a similar behaviour to other plugins when the annotation is not configured on the entity. Backstage has a `MissingAnnotationEmptyState` that provides this kind of layout:

<img width="1425" alt="Screenshot 2021-11-22 at 16 20 59" src="https://user-images.githubusercontent.com/70737734/142827007-669f1468-1c7b-4648-80c6-7fa54afd8cc6.png">

**Describe expected behaviour**

Show consistent behaviour across different Backstage plugins when annotation is missing.

**Comment by aarlaud** [comment]
ACK.
