### ISSUE TITLE
[🐛] Update Blog Post Instructions

### ISSUE THREAD

**Issue by afscrome** [snyk-tech-services/backstage-plugin-snyk#87]
The installation instructions at https://snyk.io/blog/backstage-integration-with-the-snyk-api/ no longer work - you instead need to follow the instructions in this repo's readme, but the blog post doesn't provide a way to get to this repo.  The blog post is the first result if you google "Snyk Backstage"

Can you update the blog post to correct the installation instructions.  (Or simply point to the installation instructions in readme so they don't deviate again in the future.

**Comment by aarlaud** [comment]
Post updated. Closing this. Thanks for flagging !
