### ISSUE TITLE
[🙏] Simplify `SNYK_TOKEN`

### ISSUE THREAD

**Issue by afscrome** [snyk-tech-services/backstage-plugin-snyk#88]
**Describe the user need**
It is a bit confusing having to include the `token` prefix inside the `SNYK_TOKEN` environment variable.

**Describe expected behaviour**

You could include this prefix in the proxy configuration, allowing `SYNK_TOKEN` to contain only the token.

```diff
proxy:
  '/snyk':
    target: https://snyk.io/api/v1
    headers:
      User-Agent: tech-services/backstage-plugin/1.0
-     Authorization:
-       $env: SNYK_TOKEN
+     Authorization: token ${SNYK_TOKEN}
```

**Comment by aarlaud** [comment]
Fixed in #113. Thank you !
