### ISSUE TITLE
[🙏] Link issues back to Snyk Dashboard

### ISSUE THREAD

**Issue by ryanaross** [snyk-tech-services/backstage-plugin-snyk#96]
**Describe the user need**
We would like the Snyk plugin to link back to the Snyk Dashboard in a more obvious way. Currently, the list of vulnerabilities is just static text, It is difficult to take actions without more information. The only link back to Snyk is at the very bottom with "More Details ->". With a very long list of vulnerabilities, this is very well hidden, and is not obviously a link back to Snyk.

**Describe expected behaviour**

Each vulnerability could be linked in some way to the actual issue, which would bring users to the Snyk Dashboard:
![image](https://user-images.githubusercontent.com/7442411/160436697-77f55e86-7314-44d8-b62a-28dd78577fe3.png)

**Additional context**
Current behavior, a list of vulnerabilities without sufficient context:
![image](https://user-images.githubusercontent.com/7442411/160434624-3c756c1c-680a-4948-8d77-3afa77eb2966.png)

**Comment by aarlaud** [comment]
Added in #115. Closing this, will be in the next version.
